# AUTOGENERATED! ALL CHANGES WILL BE LOST if you edit this file!
# Edit nbs/03_mcp_safecmd.ipynb instead.

from __future__ import annotations
import json
import subprocess
import sys

try:
    from mcp.server.fastmcp import FastMCP
    HAS_MCP = True
except ImportError:
    HAS_MCP = False


def _get_allowlist() -> list[str]:
    from claude_plugins.hooks.safecmd_hook import load_allowlist, DEFAULT_ALLOWLIST
    try:
        return load_allowlist()
    except Exception:
        return DEFAULT_ALLOWLIST


def validate_command_tool(command: str) -> dict:
    """Validate a shell command against the safecmd allowlist."""
    from claude_plugins.hooks.safecmd_hook import validate_command
    allowlist = _get_allowlist()
    allowed, reason = validate_command(command, allowlist)
    return {
        'allowed': allowed,
        'reason': reason,
        'command': command,
        'allowlist_size': len(allowlist),
    }


def run_safe_tool(command: str, timeout: int = 60) -> dict:
    """Validate and run a shell command safely. Only runs if allowlist check passes."""
    validation = validate_command_tool(command)
    if not validation['allowed']:
        return {
            'success': False,
            'error': f'Command blocked: {validation["reason"]}',
            'command': command,
        }
    try:
        result = subprocess.run(
            command, shell=True, capture_output=True, text=True, timeout=timeout
        )
        return {
            'success': result.returncode == 0,
            'returncode': result.returncode,
            'stdout': result.stdout,
            'stderr': result.stderr,
            'command': command,
        }
    except subprocess.TimeoutExpired:
        return {'success': False, 'error': f'Command timed out after {timeout}s', 'command': command}
    except Exception as e:
        return {'success': False, 'error': str(e), 'command': command}


def create_server() -> 'FastMCP':
    mcp = FastMCP('safecmd')

    @mcp.tool()
    def validate_command(command: str) -> str:
        """Check if a shell command is in the safecmd allowlist before running it."""
        return json.dumps(validate_command_tool(command), indent=2)

    @mcp.tool()
    def run_safe(command: str, timeout: int = 60) -> str:
        """Validate and execute a shell command safely. Blocked if not in allowlist."""
        return json.dumps(run_safe_tool(command, timeout=timeout), indent=2)

    return mcp


def main():
    if not HAS_MCP:
        print('mcp package not installed. Run: uv add mcp', file=sys.stderr)
        sys.exit(1)
    mcp = create_server()
    mcp.run()


if __name__ == '__main__':
    main()
