# AUTOGENERATED! ALL CHANGES WILL BE LOST if you edit this file!
# Edit nbs/02_mcp_exhash.ipynb instead.

from __future__ import annotations
import json
import subprocess
import sys
from pathlib import Path

try:
    from mcp.server.fastmcp import FastMCP
    HAS_MCP = True
except ImportError:
    HAS_MCP = False


def run_lnhashview(file_path: str) -> dict:
    """Run lnhashview on a file and return the hash-addressed view."""
    p = Path(file_path)
    if not p.exists():
        return {'error': f'File not found: {file_path}'}
    try:
        result = subprocess.run(
            ['lnhashview', file_path],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0:
            return {'output': result.stdout, 'file': file_path}
        return {'error': result.stderr or 'lnhashview failed'}
    except FileNotFoundError:
        return {'error': 'exhash/lnhashview not installed. Run: uv add exhash'}
    except subprocess.TimeoutExpired:
        return {'error': 'lnhashview timed out'}


def run_exhash_edit(file_path: str, commands: str, dry_run: bool = False) -> dict:
    """Apply exhash edit commands to a file.

    `commands` is a string of exhash substitution commands, one per line.
    Example:  's/HASH123/new content/'
    """
    p = Path(file_path)
    if not p.exists():
        return {'error': f'File not found: {file_path}'}

    cmd = ['exhash']
    if dry_run:
        cmd.append('--dry-run')
    cmd.append(file_path)

    try:
        result = subprocess.run(
            cmd, input=commands, capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0:
            return {'output': result.stdout or 'Edit applied successfully', 'file': file_path}
        return {'error': result.stderr or 'exhash edit failed'}
    except FileNotFoundError:
        return {'error': 'exhash not installed. Run: uv add exhash'}
    except subprocess.TimeoutExpired:
        return {'error': 'exhash timed out'}


def create_server() -> 'FastMCP':
    """Create and configure the exhash MCP server."""
    mcp = FastMCP('exhash')

    @mcp.tool()
    def lnhashview(file_path: str) -> str:
        """Display a file with hash-addressed line prefixes using exhash.
        Use this before exhash_edit to get the line hashes needed for editing.
        """
        return json.dumps(run_lnhashview(file_path), indent=2)

    @mcp.tool()
    def exhash_edit(file_path: str, commands: str, dry_run: bool = False) -> str:
        """Edit a file using exhash hash-addressed commands.
        First call lnhashview to get line hashes, then pass exhash substitution
        commands (e.g. s/HASH/new_content/). Set dry_run=True to preview changes.
        """
        return json.dumps(run_exhash_edit(file_path, commands, dry_run=dry_run), indent=2)

    return mcp


def main():
    """Run the exhash MCP server over stdio."""
    if not HAS_MCP:
        print('mcp package not installed. Run: uv add mcp', file=sys.stderr)
        sys.exit(1)
    mcp = create_server()
    mcp.run()


if __name__ == '__main__':
    main()
