# AUTOGENERATED! ALL CHANGES WILL BE LOST if you edit this file!
# Edit nbs/02_mcp_exhash.ipynb instead.

from __future__ import annotations
import subprocess
import sys
from pathlib import Path

try:
    from mcp.server import Server
    from mcp.server.stdio import stdio_server
    from mcp import types
    HAS_MCP = True
except ImportError:
    HAS_MCP = False


def run_lnhashview(file_path: str) -> dict:
    """Run lnhashview on a file and return the hash-addressed view.

    Returns a dict with 'output' (the view) or 'error'.
    """
    p = Path(file_path)
    if not p.exists():
        return {'error': f'File not found: {file_path}'}
    try:
        result = subprocess.run(
            ['lnhashview', file_path],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0:
            return {'output': result.stdout, 'file': file_path}
        return {'error': result.stderr or 'lnhashview failed'}
    except FileNotFoundError:
        return {'error': 'exhash/lnhashview not installed. Run: uv add exhash'}
    except subprocess.TimeoutExpired:
        return {'error': 'lnhashview timed out'}


def run_exhash_edit(file_path: str, commands: str, dry_run: bool = False) -> dict:
    """Apply exhash edit commands to a file.

    `commands` is a string of exhash substitution commands, one per line.
    Example:  's/HASH123/new content/'

    Returns a dict with 'output' on success or 'error'.
    """
    p = Path(file_path)
    if not p.exists():
        return {'error': f'File not found: {file_path}'}

    cmd = ['exhash']
    if dry_run:
        cmd.append('--dry-run')
    cmd.append(file_path)

    try:
        result = subprocess.run(
            cmd,
            input=commands,
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0:
            return {'output': result.stdout or 'Edit applied successfully', 'file': file_path}
        return {'error': result.stderr or 'exhash edit failed'}
    except FileNotFoundError:
        return {'error': 'exhash not installed. Run: uv add exhash'}
    except subprocess.TimeoutExpired:
        return {'error': 'exhash timed out'}


def create_server() -> 'Server':
    """Create and configure the exhash MCP server."""
    server = Server('exhash')

    @server.list_tools()
    async def list_tools() -> list[types.Tool]:
        return [
            types.Tool(
                name='lnhashview',
                description=(
                    'Display a file with hash-addressed line prefixes using exhash. '
                    'Use this before exhash_edit to get the line hashes needed for editing.'
                ),
                inputSchema={
                    'type': 'object',
                    'properties': {
                        'file_path': {'type': 'string', 'description': 'Absolute or relative path to the file'},
                    },
                    'required': ['file_path'],
                },
            ),
            types.Tool(
                name='exhash_edit',
                description=(
                    'Edit a file using exhash hash-addressed commands. '
                    'First call lnhashview to get line hashes, then pass exhash substitution '
                    'commands (e.g. s/HASH/new_content/). Supports dry_run mode.'
                ),
                inputSchema={
                    'type': 'object',
                    'properties': {
                        'file_path': {'type': 'string', 'description': 'Path to the file to edit'},
                        'commands': {'type': 'string', 'description': 'exhash commands, one per line'},
                        'dry_run': {'type': 'boolean', 'description': 'If true, preview changes without applying', 'default': False},
                    },
                    'required': ['file_path', 'commands'],
                },
            ),
        ]

    @server.call_tool()
    async def call_tool(name: str, arguments: dict) -> list[types.TextContent]:
        if name == 'lnhashview':
            result = run_lnhashview(arguments['file_path'])
        elif name == 'exhash_edit':
            result = run_exhash_edit(
                arguments['file_path'],
                arguments['commands'],
                dry_run=arguments.get('dry_run', False),
            )
        else:
            result = {'error': f'Unknown tool: {name}'}

        import json
        return [types.TextContent(type='text', text=json.dumps(result, indent=2))]

    return server


def main():
    """Run the exhash MCP server over stdio."""
    if not HAS_MCP:
        print('mcp package not installed. Run: uv add mcp', file=sys.stderr)
        sys.exit(1)
    import asyncio
    server = create_server()
    asyncio.run(stdio_server(server))


if __name__ == '__main__':
    main()
