# AUTOGENERATED! ALL CHANGES WILL BE LOST if you edit this file!
# Edit nbs/04_mcp_safepyrun.ipynb instead.

from __future__ import annotations
import asyncio
import json
import sys

try:
    from mcp.server.fastmcp import FastMCP
    HAS_MCP = True
except ImportError:
    HAS_MCP = False

try:
    from safepyrun import RunPython
    HAS_SAFEPYRUN = True
except ImportError:
    HAS_SAFEPYRUN = False

# Session-scoped runner — persists state across tool calls within a server session
_runner: 'RunPython | None' = None


def get_runner() -> 'RunPython':
    """Get or create the session-scoped RunPython instance."""
    global _runner
    if _runner is None:
        if not HAS_SAFEPYRUN:
            raise ImportError('safepyrun not installed. Run: uv add safepyrun')
        _runner = RunPython()
    return _runner


def create_server() -> 'FastMCP':
    mcp = FastMCP('safepyrun')

    @mcp.tool()
    async def run_python(code: str) -> str:
        """Execute Python code in a safepyrun sandbox.
        Code has access to curated stdlib. Variables ending with _ are exported
        to the session namespace for reuse across calls.
        """
        try:
            runner = get_runner()
            result = await runner(code)
            return json.dumps({
                'success': True,
                'stdout': result.stdout if hasattr(result, 'stdout') else str(result),
                'stderr': result.stderr if hasattr(result, 'stderr') else '',
                'result': result.result if hasattr(result, 'result') else None,
            }, indent=2)
        except ImportError as e:
            return json.dumps({'success': False, 'error': str(e)}, indent=2)
        except Exception as e:
            return json.dumps({'success': False, 'error': f'{type(e).__name__}: {e}'}, indent=2)

    @mcp.tool()
    def reset_sandbox() -> str:
        """Reset the Python sandbox, clearing all session state."""
        global _runner
        _runner = None
        return json.dumps({'success': True, 'message': 'Sandbox reset'}, indent=2)

    return mcp


def main():
    if not HAS_MCP:
        print('mcp package not installed. Run: uv add mcp', file=sys.stderr)
        sys.exit(1)
    mcp = create_server()
    mcp.run()


if __name__ == '__main__':
    main()
