# AUTOGENERATED! ALL CHANGES WILL BE LOST if you edit this file!
# Edit nbs/06_setup.ipynb instead.

from __future__ import annotations
import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

DEV_PACKAGES = [
    'python-fasthtml',
    'MonsterUI',
    'litesearch',
    'lisette',
    'exhash',
    'safecmd',
    'safepyrun',
    'codesigs',
    'nbdev',
    'jupyter',
    'ipykernel',
    'mcp',
    'claude-plugins',
]

DEFAULT_SAFECMD_ALLOWLIST = {
    "allowed_commands": [
        "uv", "pip", "pip3", "pipx",
        "python", "python3", "ipython",
        "nbdev-export", "nbdev-test", "nbdev-docs", "nbdev-prepare",
        "nbdev-clean", "nbdev-install-hooks", "nbdev-new",
        "git",
        "pytest", "coverage",
        "jupyter", "nbconvert",
        "ls", "cat", "head", "tail", "grep", "find", "wc", "sort", "uniq",
        "mkdir", "touch", "cp", "mv",
        "claude",
        "make", "cargo",
        "echo", "printf", "sed", "awk", "cut", "tr",
        "curl", "wget",
    ],
    "_comment": "Edit this list to customise which commands Claude Code can run via Bash."
}

HOOKS_CONFIG = {
    "hooks": [
        {
            "event": "PreToolUse",
            "matcher": "Bash",
            "action": {
                "type": "command",
                "command": "uv run python -m claude_plugins.hooks.safecmd_hook"
            }
        },
        {
            "event": "PostToolUse",
            "matcher": "Edit|Write",
            "action": {
                "type": "command",
                "command": "uv run python -m claude_plugins.hooks.exhash_hook"
            }
        },
        {
            "event": "SessionStart",
            "action": {
                "type": "command",
                "command": "uv run python -m claude_plugins.hooks.index_hook"
            }
        }
    ]
}

MCP_CONFIG = {
    "mcpServers": {
        "exhash": {
            "type": "stdio",
            "command": "uv",
            "args": ["run", "python", "-m", "claude_plugins.mcp_exhash"]
        },
        "safecmd": {
            "type": "stdio",
            "command": "uv",
            "args": ["run", "python", "-m", "claude_plugins.mcp_safecmd"]
        },
        "safepyrun": {
            "type": "stdio",
            "command": "uv",
            "args": ["run", "python", "-m", "claude_plugins.mcp_safepyrun"]
        }
    }
}

# opencode (opencode.ai) reads MCP servers from opencode.json
OPENCODE_CONFIG = {
    "mcp": {
        "exhash": {
            "type": "local",
            "command": ["uv", "run", "python", "-m", "claude_plugins.mcp_exhash"]
        },
        "safecmd": {
            "type": "local",
            "command": ["uv", "run", "python", "-m", "claude_plugins.mcp_safecmd"]
        },
        "safepyrun": {
            "type": "local",
            "command": ["uv", "run", "python", "-m", "claude_plugins.mcp_safepyrun"]
        }
    }
}

CLAUDE_MD_BLOCK = '''
<!-- claude-plugins: START -->
## Claude Code Setup (claude-plugins)

Active hooks: safecmd (Bash PreToolUse), exhash (Edit/Write PostToolUse), code indexer (SessionStart).
MCP servers available: exhash, safecmd, safepyrun.
Skills: /exhash /safecmd /safepyrun /litesearch /fasthtml /monsterui /lisette /nbdev /codesigs
Code index: .claude/code_index.db (built on session start via codesigs + litesearch)
<!-- claude-plugins: END -->
'''

VALID_COMPONENTS = {'hooks', 'mcp', 'skills'}


def check_uv() -> bool:
    "Return True if uv is available in PATH."
    return shutil.which('uv') is not None


def run(cmd: list[str], cwd: Path | None = None, check: bool = True) -> subprocess.CompletedProcess:
    "Run a subprocess command and return the result."
    return subprocess.run(cmd, cwd=cwd, check=check, capture_output=False)


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + '\n')


def merge_json_file(path: Path, new_data: dict) -> None:
    """Merge new_data into existing JSON at path; lists are extended without duplicates."""
    from claude_plugins.core import merge_json
    merge_json(path, new_data)


def upsert_claude_md(target: Path) -> None:
    """Add or update the claude-plugins block in CLAUDE.md."""
    claude_md = target / 'CLAUDE.md'
    if claude_md.exists():
        content = claude_md.read_text()
        if '<!-- claude-plugins: START -->' in content:
            content = re.sub(
                r'<!-- claude-plugins: START -->.*?<!-- claude-plugins: END -->',
                '', content, flags=re.DOTALL
            ).strip()
        claude_md.write_text(content + '\n' + CLAUDE_MD_BLOCK)
    else:
        claude_md.write_text(CLAUDE_MD_BLOCK)


def install_packages_uv(target: Path) -> None:
    """Install dev packages into the target project venv using uv pip install."""
    print('\n[2/N] Installing packages with UV...')
    # Ensure there's a venv to install into
    run(['uv', 'venv', '--seed'], cwd=target, check=False)
    # Install all packages at once — faster than one-by-one
    result = run(['uv', 'pip', 'install'] + DEV_PACKAGES, cwd=target, check=False)
    if result.returncode != 0:
        print('  WARNING: some packages may have failed — check output above')


def index_installed_packages(target: Path) -> int:
    """Index installed packages from the venv into the code search index.

    Uses litesearch.data.pkg2chunks to extract code from installed packages.
    Returns number of chunks indexed.
    """
    db_path = target / '.claude' / 'code_index.db'
    db_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        from litesearch import database
        from litesearch.utils import FastEncode
        from litesearch.data import pkg2chunks

        db = database(str(db_path))
        store = db.get_store(name='deps')
        encoder = FastEncode()

        total = 0
        for pkg in DEV_PACKAGES:
            pkg_name = pkg.replace('-', '_').lower()
            try:
                chunks = pkg2chunks(pkg_name)
                rows = []
                for chunk in chunks:
                    text = chunk.get('content', '') if isinstance(chunk, dict) else str(chunk)
                    if not text.strip():
                        continue
                    rows.append({
                        'content': text,
                        'embedding': encoder.encode_document(text).tobytes(),
                        'metadata': json.dumps({'source': pkg_name, **({k: v for k, v in chunk.items() if k != 'content'} if isinstance(chunk, dict) else {})}),
                    })
                if rows:
                    store.insert_all(rows)
                    total += len(rows)
                    print(f'    indexed {len(rows)} chunks from {pkg_name}')
            except Exception as e:
                pass  # Package may not be indexable
        return total
    except ImportError:
        print('  WARNING: litesearch not available, skipping dep indexing')
        return 0


def setup(
    target_dir: str | None = None,
    skip_packages: bool = False,
    components: set[str] | None = None,
    index_deps: bool = False,
) -> None:
    """Run the claude-plugins setup in target_dir (default: cwd).

    Args:
        target_dir: Project directory (default: cwd)
        skip_packages: Skip UV package installation
        components: Set of components to install ('hooks', 'mcp', 'skills').
                    None means install all.
        index_deps: Also index installed packages into the code search index
    """
    target = Path(target_dir or Path.cwd()).resolve()
    install_all = components is None
    do_hooks = install_all or 'hooks' in (components or set())
    do_mcp = install_all or 'mcp' in (components or set())
    do_skills = install_all or 'skills' in (components or set())

    print(f'claude-plugins setup — target: {target}')
    components_str = 'all' if install_all else ', '.join(sorted(components or set()))
    print(f'components: {components_str}')
    print('=' * 60)

    # Step 1: UV check
    print('\n[1] Checking UV...')
    if not check_uv():
        print('  ERROR: UV not found.')
        print('  Install: curl -LsSf https://astral.sh/uv/install.sh | sh')
        sys.exit(1)
    print('  OK UV found')

    # Step 2: Packages
    if not skip_packages:
        install_packages_uv(target)
        print('  OK Packages installed')

    # Step 3: nbdev hooks (only if nbdev component selected or all)
    if install_all or do_hooks:
        print('\n[3] Installing nbdev git+Jupyter hooks...')
        try:
            run(['uv', 'run', 'nbdev-install-hooks'], cwd=target, check=False)
            print('  OK nbdev hooks installed')
        except Exception as e:
            print(f'  WARNING: nbdev-install-hooks failed: {e}')

    # Step 4: Claude Code hooks
    if do_hooks:
        print('\n[4] Writing .claude/settings.json (Claude Code hooks)...')
        merge_json_file(target / '.claude' / 'settings.json', HOOKS_CONFIG)
        if not (target / '.claude' / 'safecmd_allowlist.json').exists():
            write_json(target / '.claude' / 'safecmd_allowlist.json', DEFAULT_SAFECMD_ALLOWLIST)
        print('  OK hooks + allowlist written')

    # Step 5: MCP servers (Claude Code + opencode)
    if do_mcp:
        print('\n[5] Writing MCP server configs...')
        merge_json_file(target / '.mcp.json', MCP_CONFIG)
        print('  OK .mcp.json (Claude Code)')
        opencode_path = target / 'opencode.json'
        if opencode_path.exists():
            merge_json_file(opencode_path, OPENCODE_CONFIG)
        else:
            write_json(opencode_path, OPENCODE_CONFIG)
        print('  OK opencode.json (opencode)')

    # Step 6: Skills
    if do_skills:
        print('\n[6] Installing skills to .claude/skills/...')
        from claude_plugins.skills_gen import install_skills
        installed = install_skills(target)
        for name in installed:
            print(f'  OK {name}')

    # Step 7: CLAUDE.md
    print('\n[7] Updating CLAUDE.md...')
    upsert_claude_md(target)
    print(f'  OK {target / "CLAUDE.md"}')

    # Step 8: Index installed packages (optional)
    if index_deps:
        print('\n[8] Indexing installed package APIs...')
        n = index_installed_packages(target)
        print(f'  OK {n} chunks indexed from installed packages')

    print('\n' + '=' * 60)
    print('claude-plugins setup complete!')
    print('\nNext steps:')
    print('  1. Start Claude Code: claude')
    print('  2. Skills available: /exhash /safecmd /safepyrun /litesearch /monsterui')
    print('  3. Edit .claude/safecmd_allowlist.json to customise allowed commands')
    if index_deps:
        print('  4. Code index includes installed package APIs — use /litesearch to query')


def main():
    parser = argparse.ArgumentParser(
        prog='claude-plugins',
        description='Claude Code dev environment setup — hooks, MCP servers, and skills',
    )
    subparsers = parser.add_subparsers(dest='command')

    setup_parser = subparsers.add_parser('setup', help='Run setup in target directory')
    setup_parser.add_argument('--target-dir', '-t', default=None,
                              help='Target project directory (default: cwd)')
    setup_parser.add_argument('--skip-packages', action='store_true',
                              help='Skip UV package installation')
    setup_parser.add_argument(
        '--components', '-c', default=None,
        help='Comma-separated subset to install: hooks,mcp,skills (default: all)'
    )
    setup_parser.add_argument('--index-deps', action='store_true',
                              help='Also index installed packages into code search index')

    args = parser.parse_args()

    if args.command == 'setup':
        components = None
        if args.components:
            components = {c.strip() for c in args.components.split(',')}
            invalid = components - VALID_COMPONENTS
            if invalid:
                print(f'ERROR: unknown components: {invalid}. Valid: {VALID_COMPONENTS}')
                sys.exit(1)
        setup(
            target_dir=args.target_dir,
            skip_packages=args.skip_packages,
            components=components,
            index_deps=args.index_deps,
        )
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
