# AUTOGENERATED! ALL CHANGES WILL BE LOST if you edit this file!
# Edit nbs/05_skills.ipynb instead.

from __future__ import annotations
import shutil
from pathlib import Path


def skills_source_dir() -> Path:
    """Return the path to the bundled skills directory inside the package."""
    return Path(__file__).parent / 'skills'


def install_skills(target_dir: Path, overwrite: bool = False) -> list[str]:
    """Copy skills from the package to target_dir/.claude/skills/.

    Returns list of skill names installed.
    """
    src = skills_source_dir()
    dst = target_dir / '.claude' / 'skills'
    dst.mkdir(parents=True, exist_ok=True)

    installed = []
    if not src.exists():
        return installed

    for skill_dir in src.iterdir():
        if not skill_dir.is_dir():
            continue
        target_skill = dst / skill_dir.name
        if target_skill.exists() and not overwrite:
            installed.append(f'{skill_dir.name} (skipped, already exists)')
            continue
        shutil.copytree(str(skill_dir), str(target_skill), dirs_exist_ok=True)
        installed.append(skill_dir.name)

    return installed
