# AUTOGENERATED! ALL CHANGES WILL BE LOST if you edit this file!
# Edit nbs/01_hooks.ipynb instead.

from __future__ import annotations
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def capture_lnhashview(file_path: str) -> str | None:
    """Run `lnhashview` on the file and return its output, or None if unavailable."""
    try:
        result = subprocess.run(
            ['lnhashview', file_path],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            return result.stdout
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return None


def append_audit(audit_path: Path, record: dict) -> None:
    "Append a record to the JSONL audit log."
    audit_path.parent.mkdir(parents=True, exist_ok=True)
    with audit_path.open('a') as f:
        f.write(json.dumps(record) + '\n')


def main():
    """Claude Code PostToolUse hook entry point. Reads JSON from stdin, logs edit audit."""
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        sys.exit(0)

    tool_name = payload.get('tool_name', '')
    if tool_name not in ('Edit', 'Write'):
        sys.exit(0)

    tool_input = payload.get('tool_input', {})
    file_path = tool_input.get('file_path', '')

    if not file_path or not Path(file_path).exists():
        sys.exit(0)

    lnhash_snapshot = capture_lnhashview(file_path)

    record = {
        'timestamp': datetime.now(timezone.utc).isoformat(),
        'tool': tool_name,
        'file': file_path,
        'lnhash_snapshot': lnhash_snapshot,
    }

    audit_path = Path.cwd() / '.claude' / 'edit_audit.jsonl'
    append_audit(audit_path, record)
    sys.exit(0)


if __name__ == '__main__':
    main()
