# AUTOGENERATED! ALL CHANGES WILL BE LOST if you edit this file!
# Edit nbs/01_hooks.ipynb instead.

from __future__ import annotations
import json
import sys
from pathlib import Path

EXCLUDED_DIRS = {'.venv', 'venv', '.git', '__pycache__', 'node_modules', '.claude', 'dist', 'build'}
INDEXED_EXTENSIONS = {'.py', '.js', '.ts', '.jsx', '.tsx', '.rs', '.go', '.java'}


def collect_source_files(root: Path) -> list[Path]:
    """Collect source files to index, excluding common non-source directories."""
    files = []
    for p in root.rglob('*'):
        if any(part in EXCLUDED_DIRS for part in p.parts):
            continue
        if p.suffix in INDEXED_EXTENSIONS and p.is_file():
            files.append(p)
    return files


def build_index(root: Path, db_path: Path) -> int:
    """Build the code index. Returns number of items indexed.

    Uses codesigs to extract signatures, then litesearch to index them.
    Falls back to plain-text indexing if either library is unavailable.
    """
    files = collect_source_files(root)
    if not files:
        return 0

    docs = []
    try:
        from codesigs import file_sigs
        for f in files:
            try:
                sigs = file_sigs(str(f))
                for sig in sigs:
                    docs.append({
                        'text': f'{sig.get("signature", "")}\n{sig.get("docstring", "")}'.strip(),
                        'metadata': json.dumps({
                            'id': f'{f}::{sig.get("name", "")}',
                            'file': str(f),
                            'name': sig.get('name', ''),
                            'kind': sig.get('kind', 'function'),
                        }),
                    })
            except Exception:
                continue
    except ImportError:
        # Fallback: index raw file content
        for f in files:
            try:
                docs.append({
                    'text': f.read_text(errors='ignore')[:4000],
                    'metadata': json.dumps({'id': str(f), 'file': str(f)}),
                })
            except Exception:
                continue

    if not docs:
        return 0

    try:
        from litesearch import database
        from litesearch.utils import FastEncode
        db = database(str(db_path))
        store = db.get_store()
        encoder = FastEncode()
        rows = [
            {
                'content': d['text'],
                'embedding': encoder.encode_document(d['text']).tobytes(),
                'metadata': d['metadata'],
            }
            for d in docs if d['text'].strip()
        ]
        if rows:
            store.insert_all(rows)
        return len(rows)
    except ImportError:
        pass

    return 0


def main():
    """Claude Code SessionStart hook entry point. Builds code search index silently."""
    try:
        # May or may not have payload on stdin for SessionStart
        payload_str = sys.stdin.read()
        payload = json.loads(payload_str) if payload_str.strip() else {}
    except Exception:
        payload = {}

    root = Path(payload.get('cwd', str(Path.cwd())))
    db_path = root / '.claude' / 'code_index.db'
    db_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        n = build_index(root, db_path)
        if n > 0:
            # Communicate back to Claude via stdout additional context
            output = {
                "hookSpecificOutput": {
                    "hookEventName": "SessionStart",
                    "additionalContext": (
                        f"Code index built: {n} signatures indexed into .claude/code_index.db\n"
                        "Use the /litesearch skill to query the index semantically."
                    )
                }
            }
            print(json.dumps(output))
    except Exception:
        pass  # Never block session start

    sys.exit(0)


if __name__ == '__main__':
    main()
