# AUTOGENERATED! ALL CHANGES WILL BE LOST if you edit this file!
# Edit nbs/01_hooks.ipynb instead.

from __future__ import annotations
import json
import sys
from pathlib import Path

# Default allowlist for common dev commands.
# The setup command writes this to .claude/safecmd_allowlist.json
DEFAULT_ALLOWLIST = [
    # Package management
    "uv", "pip", "pip3", "pipx",
    # Python
    "python", "python3", "ipython",
    # nbdev
    "nbdev-export", "nbdev-test", "nbdev-docs", "nbdev-prepare",
    "nbdev-clean", "nbdev-install-hooks", "nbdev-new",
    # Git (read-only and safe write ops)
    "git",
    # Testing
    "pytest", "coverage",
    # Jupyter
    "jupyter", "nbconvert",
    # File ops (safe subset)
    "ls", "cat", "head", "tail", "grep", "find", "wc", "sort", "uniq",
    "mkdir", "touch", "cp", "mv",
    # Claude Code
    "claude",
    # Build tools
    "make", "cargo",
    # Text processing
    "echo", "printf", "sed", "awk", "cut", "tr",
    # Network (read-only)
    "curl", "wget",
]


def load_allowlist(claude_dir: Path | None = None) -> list[str]:
    """Load the safecmd allowlist from .claude/safecmd_allowlist.json, falling back to DEFAULT_ALLOWLIST."""
    if claude_dir is None:
        claude_dir = Path.cwd() / '.claude'
    allowlist_path = claude_dir / 'safecmd_allowlist.json'
    if allowlist_path.exists():
        data = json.loads(allowlist_path.read_text())
        return data.get('allowed_commands', DEFAULT_ALLOWLIST)
    return DEFAULT_ALLOWLIST


def validate_command(command: str, allowlist: list[str]) -> tuple[bool, str]:
    """Check if `command` is permitted. Returns (allowed, reason).

    First tries safecmd library if available; falls back to prefix-matching against allowlist.
    """
    # First try safecmd library for AST-based validation
    try:
        from safecmd import check  # safecmd public API
        result = check(command, allowed=allowlist)
        if result.allowed:
            return True, 'allowed by safecmd'
        else:
            return False, f'blocked by safecmd: {result.reason}'
    except ImportError:
        pass  # fallback below
    except Exception:
        pass  # on any safecmd error, fall through to simple check

    # Fallback: simple first-token check
    stripped = command.strip()
    if not stripped:
        return True, 'empty command'

    # Block obviously destructive patterns regardless of allowlist
    BLOCKED_PATTERNS = ['rm -rf /', 'rm -rf ~', ':(){ :|:& };:', '> /dev/', 'dd if=', 'mkfs']
    for pat in BLOCKED_PATTERNS:
        if pat in stripped:
            return False, f'blocked: contains dangerous pattern "{pat}"'

    first_token = stripped.split()[0]
    # Strip path prefix (e.g. /usr/bin/python -> python)
    binary = Path(first_token).name

    if binary in allowlist:
        return True, f'allowed: {binary} is in allowlist'

    return False, f'blocked: "{binary}" is not in the allowed commands list'


def main():
    """Claude Code PreToolUse hook entry point. Reads JSON from stdin, writes decision to stdout."""
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        sys.exit(0)  # No input or bad JSON: don't block

    tool_name = payload.get('tool_name', '')
    if tool_name != 'Bash':
        sys.exit(0)  # Not a Bash call: pass through

    command = payload.get('tool_input', {}).get('command', '')
    allowlist = load_allowlist()
    allowed, reason = validate_command(command, allowlist)

    if allowed:
        sys.exit(0)
    else:
        output = {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": (
                    f"safecmd blocked this command: {reason}\n"
                    f"Command: {command!r}\n"
                    f"To allow this command, add it to .claude/safecmd_allowlist.json"
                )
            }
        }
        print(json.dumps(output))
        sys.exit(1)


if __name__ == '__main__':
    main()
